import { Header } from "@/components/header/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Barlow } from "next/font/google";
import { Footer } from "@/components/footer/Footer";

const barlow = Barlow({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={barlow.className} lang="en">
      <body className="bg-background">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
